### PR TITLE
How to download amazon prime video using this tool?

### PR DESCRIPTION
**Pull request by sundelirajesh**
How to use this program and download amazon prime video ?

### CODE REVIEW

**Comment by dheeraj-rn** [comment]
Em. I'm confused. What really happened here?

**Comment by FloridaStream** [comment]
Good question @dheeraj-rn good question, if you find out what's going on here, tell me, because I do not even know. 

@techbliss you would not want to activate issues, so people ask questions more properly?

**Comment by dheeraj-rn** [comment]
Oh so that's why there is no issues tab in this repo? 
I'm actually confused about ` techbliss merged 4 commits into techbliss:master from dheeraj-rn:master 6 days ago `. I never gave a PR :dizzy_face:

**Comment by techbliss** [comment]
I am confused as well I forked this project, now i cant see where i forked it from.
It is like i have taken over the repo.

**Comment by FloridaStream** [comment]
@techbliss please **make this repository private** to protect the files bro, thanks.

**Pull request merged**
